### ISSUE TITLE
Import-AzureComputeGalleryImageVersion ignores ComputeGalleryVersion

### ISSUE THREAD

**Issue by FergyD** [jamasten/Azure#10]
Line 167 is hardcoded to use a version number of 1.0.0.
It needs to use the param entered: $ComputeGalleryVersion

**Comment by jamasten** [comment]
Thank you @FergyD for the feedback.  I updated the code and pushed the change.  That can be validated here: https://github.com/jamasten/Azure/commit/0217a8ab7ed1b1255ef111138a0e98bef014f233

Please let me know if you find any other issues!
