### ISSUE TITLE
-OsType Parameter is Missing. New Imagedefinitions will be created as Windows

### ISSUE THREAD

**Issue by FrankOder2402** [jamasten/Azure#11]
Could you please be so kind and add the -OsType <OperatingSystemTypes> into the Import Script

	[parameter(Mandatory=$false)]
    [string]$OsType, 

Add-AzVhd `
    -LocalFilePath $VhdFilePath `
    -ResourceGroupName $ComputeGalleryResourceGroupName `
    -Location $Location `
    -DiskName $DiskName `
    -NumberOfUploaderThreads 32 `
    **-DiskOsType $OsType**

otherwise a new Managed Disk will be marked as Windows. I can not found that add-AzVhd has a default value but it always create the new vhd as Windows

THX a lot

**Comment by jamasten** [comment]
Hi @FrankOder2402. Thanks for the feedback. I have updated the export script with the following code to fix your issue: 

```powershell
# Gets the OS Type
$OsType = (Get-AzGalleryImageDefinition `
    -GalleryImageDefinitionName $ComputeGalleryDefinitionName `
    -GalleryName $ComputeGalleryName `
    -ResourceGroupName $ComputeGalleryResourceGroupName).OsType

# Creates a Disk Configuration for a Managed Disk using the Image Version in the Compute Gallery
$DiskConfig = New-AzDiskConfig `
    -Location $Location `
    -CreateOption FromImage `
    -GalleryImageReference @{Id = $ImageVersion.Id} `
    -OsType $OsType
```

**Comment by jamasten** [comment]
Alright so I got a little ahead of myself.  That fixed the issue on the export script.  I just realized I needed to update the import script as well.  more to come...

**Comment by jamasten** [comment]
The import script has been fixed as well.  I added the param like you suggested and updated the Add-AzVhd cmdlet to specify it:

```powershell
    [parameter(Mandatory=$false)]
    [ValidateSet('Windows','Linux')]
    [string]$OsType = 'Windows', 
```

```powershell
# Uploads the VHD from the filesystem to Azure as a Managed Disk
Add-AzVhd `
    -LocalFilePath $VhdFilePath `
    -ResourceGroupName $ComputeGalleryResourceGroupName `
    -Location $Location `
    -DiskName $DiskName `
    -DiskOsType $OsType `
    -NumberOfUploaderThreads 32
```

**Comment by jamasten** [comment]
I ran an end-to-end test with an Ubuntu server and had no issues.  Let me know if you find any.  Thanks!
