### ISSUE TITLE
[Export-AzureComputeGalleryImageVersion / Import-AzureComputeGalleryImageVersion] Use ImageVersionName as part of  $DiskPrefix

### ISSUE THREAD

**Issue by Hanse00** [jamasten/Azure#12]
I'm happy to make this change myself if it makes sense, but I didn't want to open a PR before bringing it up for discussion.

Is there a reason ImageVersionName isn't used as part of $DiskPrefix?

I believe it would allow exporting and importing multiple versions of an image simultaneously, as it would prevent the process on blocking itself in case of duplicate ImageDefinitionNames.

**Comment by jamasten** [comment]
Hi @Hanse00. I assume you're concerned about the export script. That's a good point.  I've never considered migrating multiple image versions simultaneously.  Please feel free to submit a PR and thanks for your feedback!

**Comment by Hanse00** [comment]
It would apply to both the export and import script, as the export script creates a VHD from the image to then download, and the import script creates a VHD from disk data and then imports it. Both processes would be blocked if you tried to do it with two different versions of the same image, due to the name collision.

I'll have the PR written up shortly :)
