### ISSUE TITLE
Getting a 404 on the AVD Repo

### ISSUE THREAD

**Issue by LTCAshraven** [jamasten/Azure#16]
Hey Jason,

Your readme.md for AVD points to https://github.com/jamasten/AzureVirtualDesktop but it's not there.

**Comment by jamasten** [comment]
@chrismrutledge yeah, Shawn Meyer took over my old solution. He's hosting it here: https://github.com/[shawntmeyer/AzureVirtualDesktop](https://github.com/shawntmeyer/AzureVirtualDesktop)
